ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 8 LPS 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat8-lps1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 7 LPS 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat7-lps1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 2 LPS 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat2-lps1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 8 LPS 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat8-lps2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 9 LPS 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat9-lps2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 2 LPS 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat2-lps2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 7 LPS 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat7-lps2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 3 LPS 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat3-lps1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 4 LPS 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat4-lps1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 5 LPS 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat5-lps2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 2 LPS 4.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat2-lps4.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 4 LPS 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat4-lps2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 9 LPS 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat9-lps1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 2 LPS 3.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat2-lps3.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 6 LPS 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat6-lps1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 5 LPS 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat5-lps1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 3 LPS 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat3-lps2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/LPS Rats Jan 2020/Rat 6 LPS 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat6-lps2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 1 Control 3.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat1-control3.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 2 Control 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat2-control2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 4 Control 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat4-control1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 1 Control 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat1-control1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 5 Control 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat5-control2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 1 Control 4.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat1-control4.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 2 Control 3.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat2-control3.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 5 Control 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat5-control1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 9 Control 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat9-control2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 2 Control 4.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat2-control4.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 7 Control 4.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat7-control4.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 3 Control 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat3-control1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 6 Control 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat6-control2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 6 Control 3.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat6-control3.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 7 Control 3.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat7-control3.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 6 Control 5.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat6-control5.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 6 Control 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat6-control1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 3 Control 3.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat3-control3.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 6 Control 4.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat6-control4.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 8 Control 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat8-control2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 7 Control 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat7-control2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 9 Control 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat9-control1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 7 Control 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat7-control1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 3 Control 4.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat3-control4.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 3 Control 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat3-control2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 8 Control 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat8-control1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 2 Control 1.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat2-control1.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 4 Control 2.MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat4-control2.mp4 -c:v hevc_cuvid
ffmpeg -y -hwaccel_output_format cuda -hwaccel_device 0 -hwaccel cuvid -c:v hevc_cuvid -i "/workspace/gs/Rat Controls Jan 2020 /Rat 1 Control 2 .MP4" -r 24 -c:v hevc_nvenc -b:v 128K -strict -2 -movflags faststart /workspace/videos/24fps_trial3/rat1-control2.mp4 -c:v hevc_cuvid